baseurl = "https://chrishildebrand.net/"
title = "Site of Chris Hildebrand"
languageCode = "en-us"

newContentEditor = "emacsclient"
pygmentsuseclasses = true

[taxonomies]
tag = "tags"

[author]
name = "Chris Hildebrand"
